default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: formerboygenius_dev
  port: 5432
  host: localhost

test:
  <<: *default
  database: formerboygenius_test
  port: 5432
  host: localhost
